### ISSUE TITLE
Table component

### ISSUE THREAD

**Issue by ruymon** [ivaoaero/atmosphere#6]
Migrate + extend a table component. The UI/styles are in the Atmodash already and it looks beautiful but the code is completely rubbish.

**Subtasks**

- [ ] Break it into small components (table header, table item etc.)
- [ ] Add a logic lib (React Table - TanStack)
- [ ] Work on responsive and code abstraction
